### ISSUE TITLE
NVRAM warning error

### ISSUE THREAD

**Issue by JonnyTech** [ViRb3/nMAC#10]
After using nMAC to patch `/nvdata/APCFG/APRDEB/WIFI` on my Wileyfox Spark, all works well but if I reboot or cycle the wifi adaptor, it shows an error message (`NVRAM WARNING: Err = 0x10`):

![error](https://user-images.githubusercontent.com/3584732/34731624-c2a8b078-f55a-11e7-942b-bc26f84e66c5.png)

I can connect to wireless networks, but that message is always shown in the networks list.

When I check the MAC it reports all zero's and some networks refuse to connect.

Restoring the backup fixes everything.

My assumption is that there is a checksum within the modified file that needs updating when the MAC is changed, but I cannot find any documentation about it.

Any ideas?

**Comment by ViRb3** [comment]
Hey,

I remember you were the person who helped me add support for this device. Was this issue present from the beginning, or did it happen just now?

Make sure you are not changing the OUI - the first 3 bytes of your new MAC should match the original.

Other than that, I can only advise you to look for other files containing your MAC. Check my other project: https://github.com/ViRb3/overseer

Good luck!

**Comment by JonnyTech** [comment]
Yes, tis I. Greetings.

I rarely reboot my phone so I did not notice for a long time. Through testing I can confirm that it happens every time.

The first three bytes are unchanged, I discovered not to do that right at the start. Even if I change the very last digit, it works correctly with that new MAC until a reboot. So the system must check the checksum at initialisation.

It is not a problem as the workaround that I mentioned fixes it, but it is confusing and should be documented for novice users.

I had checked my device with overseer and it did find a text file in /sys which we discounted when testing in the original issue.

There seems to be no documentation on the file in /nvdata or the checksum so I shall leave this issue open until something is found.

**Comment by ViRb3** [comment]
Just a random thought - quite possibly the system is checking the NVRAM's integrity, similar to how SafetyNet checks the /system partition. Maybe you could try modifying the file with Magisk instead and seeing if the issue is still there? 🙄

**Comment by JonnyTech** [comment]
Which file? Do you mean to change the text file in /nvram to match the changes that nMAC makes to the binary file?

I do not use Magisk. It caused issues with my device.

**Comment by ViRb3** [comment]
Pardon me. I meant to say that the system may be checking for the integrity of: `/nvdata/APCFG/APRDEB/WIFI`. I'm not sure what would happen if you modify the file in NVDATA.

**Comment by JonnyTech** [comment]
Sorry for the delayed reply: a device system update resolved the issue.
