### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by cgk78** [ViRb3/nMAC#11]
Problem with Nexus 5 Lineages OS![](https://i.imgur.com/kMgXGHz.png)

**Comment by cgk78** [comment]
![](https://i.imgur.com/LHEXWPn.png)

**Comment by cgk78** [comment]
![Here is my Nexus 5](https://i.imgur.com/hrLCJUC.png)

**Comment by ViRb3** [comment]
Hey there!

Could you please check the existence of this file: `/persist/wifi/.macaddr`? Its content in bytes (use hex editor) should equal your MAC and nothing more.

Thanks

**Comment by cgk78** [comment]
![Zero byte in a .macaddr](https://i.imgur.com/iExYWeq.png)

**Comment by ViRb3** [comment]
Indeed, the file is empty and therefore corrupted. I am actually surprised your WiFi still works. Try this one - extract it, replace your file and **make sure to match the right permissions!**

[macaddr.zip](https://github.com/ViRb3/nMAC/files/1742606/macaddr.zip)

Good luck!

**Comment by cgk78** [comment]
Its working!, Thank you sir for your help and your hard work.

**Comment by ViRb3** [comment]
Very glad to hear :) Make sure to change your MAC address now, as it's currently set to an LG device (first 6 bytes).
