### ISSUE TITLE
Support for Nexus 5 Hammerhead with Lineage OS

### ISSUE THREAD

**Issue by PJK2011** [ViRb3/nMAC#9]
Hi,

I saw that this app supports Nexus 5 Hammerhead, but I was surprised it is not supporting Lineage OS on Hammerhead, or at least the app reports that it doesn't when I run it.

The persist directory is still in root, and still contains the file wlan_mac.bin with the same contents in this format:

Intf0MacAddress=xxxxxxxxxxxxxxx
Intf1MacAddress=00AA00BB00C2
Intf2MacAddress=00AA00BB00C3
Intf3MacAddress=00AA00BB00C4

I'm having the MAC address 02:00:00:00:00:00 causing the wifi to not work problem. I already edited it with file explorer, but even though the changes in my file persist, the 02:00:00:00:00:00 MAC address still shows in Phone Status. I was hoping your app would overcome this.

I don't find a /etc/firmware/wlan/qca_cld file that has been suggested as being a culprit in the persistence of the 02:00:00:00:00:00 MAC address. That directory only contains cpp_firmware_vx_x_x.fw files.

Thanks

John

**Comment by ViRb3** [comment]
Hey John!

My brother has a Nexus 5 so I'll be able to do a more in-depth check tonight. Looking at the template, the file that actually stores your MAC address is this one: `/persist/wifi/.macaddr`. Note that it's written directly as bytes, not as ASCII. Tell me how's your situation with that file and we'll see what we can do.

Best regards

**Comment by PJK2011** [comment]
Hi,

Thanks for your response. My bad. I got the text online from someone who
posted the data in a wlan_mac.bin file, but I actually copied the text into
the .macaddr file as you mentioned.

I tried using a MAC address from a web random MAC provider service. That
one didn't work.

I noticed the bcmdhd.cal file has

macaddr=00:90:4c:c5:12:38

I didn't know if this was supposed to be the same as my original real MAC
address, but I tried it anyway, and it didn't work.

Then I tried the other person's MAC that came in his file, and it didn't
work either. Through all these changes, Phone Status always
shows 02:00:00:00:00:00.

Now that you mention that .macaddr is supposed to be binary, not ASCII,
before I edited it, I noticed it did have just about 3 non-text characters.
Thinking they were corrupt text, I overwrote it with the text data I sent
you.

I'm also sending you screen shots obtained from the *#*#4636#*#*  Phone
Information Service Menu which show WiFi information completely blank. I'm
also sending screenshots from my phone information screens.

Thanks,

John

**Comment by PJK2011** [comment]
In the meantime I found an XDA post from someone sharing his .macaddr file
for others with the same problem. Using it didn't help.

Another person commented on watching permissions where some files have root
as the owner and group, and some have WiFi and system. I set them all to
match WiFi and system, but it didn't work either.

**Comment by PJK2011** [comment]
I also tried your app on another Nexus 5 running Lineage OS and it accepted
the phone. I don't know why it would accept the one phone and not the
other. They are both US versions, D820, unless there are minor variations
in production dates. I wanted to run your app to get the files from the
working phone to install on the non-working phone, but the only file in the
.nMAC directory is wlan_mac.bin, which is also in binary format (6 bytes)
instead of the ASCII MAC configuration.

**Comment by ViRb3** [comment]
Hey,

Sorry for the delay. The only thing nMAC checks in the Nexus 5X is whether the file `"/persist/wifi/.macaddr"` is equal to 6 bytes in length. Try to copy this file from your working device to your non-working one, and make sure you preserve all the permissions + group + owner. If you are using a file manager I recommend `Solid Explorer`. 

On another note, don't randomize MAC addresses entirely, as an invalid OUI (first 3 bytes) can cause issues.

To create a valid `.macaddr` file, you have to use a hex editor to write the bytes. On Windows I recommend [HxD](https://mh-nexus.de/en/hxd/). Make sure to write the bytes in the **left** pane, which is byte view, not the right, which is ASCII.

**Comment by PJK2011** [comment]
No problem. I appreciate you getting back to me.

In the meantime, since so many people reported this as an issue with
Marshmellow OTA updates, and it continues to be reported as an issue in
Nougat updates, I decided to revert to KitKat and then Lollipop.

I didn't spend much time in KitKat because Google issued warnings that the
utilities I wanted to use were not compatible with the OS, and there was no
Persist directory, unless I forgot to select Show Hidden in the file
manager. I did notice that the infamous 02:00:00:00:00:00 MAC address was
gone, and Phone Status was now showing WiFi MAC Address Unavailable.

When I flashed Lollipop, Phone Status remained WiFi MAC Address
Unavailable. But now your app was able to run. I was surprised to see that
your app reported that the MAC address I borrowed from a blogger who gave
out his personal MAC that I had installed in Lineage OS had survived the
flashes for KitKat and Lollipop. Looking at the blog post again, I noticed
a typo in that the MAC address he typed in the blog was not the same as in
the wlan_mac.bin file he gave for downloading (2 characters different).

So thinking maybe I was just using a bad MAC address in all this testing, I
let your app randomize a MAC address. Unfortunately Phone Status remained
WiFi MAC Address Unavailable. In all these steps, Chainfire's Pry-Fi was
never able to read my MAC address, so kudos to your app for being able to
finally read my MAC address when even Phone Status says the MAC address is
unavailable.

Examining the file structure as compared to your XDA post, of the two
directories and four files you indicate, only the Persist directory and
.macaddr file have ever appeared in any version of Android I've tried on
this phone. After using your app to randomize the MAC address, it is
correctly reported in .macaddr. (Is your XDA post a typo? It reads
/persist/bdaddr.txt     : interface 0 (main) MAC address. I always see
.bdaddr - not txt - in the Bluetooth directory of Persist and .macaddr in
the WiFi directory of Persist.)

Switching to your app's random MAC address did not solve my WiFi problem,
so at this point, I'm satisfied that between that and the 02:00:00:00:00:00
bug being gone, that this is a hardware fault and not an Android
configuration fault. Also, the BusyBox command:

# busybox iplink show eth0

responds

iplink: can't find device 'eth0'

I think another command I ran returned wlan0 not present, but I can't
remember now. I've tried so many things in this effort.

Thanks for your support and your app.

**Comment by PJK2011** [comment]
It looks like I spoke to soon!

After wiping cache and a factory reset, flashing stock factory Marshmallow
brings back the lovely Phone Status WiFi Mac Address of 02:00:00:00:00:00.

Some suggest this is a Marshmallow bug, but maybe it's a feature per this
announcement:

Access to Hardware Identifier
------------------------------

To provide users with greater data protection, starting in this release,
Android removes programmatic access to the device’s local hardware
identifier for apps using the Wi-Fi and Bluetooth APIs. The
WifiInfo.getMacAddress()
<https://developer.android.com/reference/android/net/wifi/WifiInfo.html#getMacAddress()>
and
the BluetoothAdapter.getAddress()
<https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#getAddress()>
methods
now return a constant value of 02:00:00:00:00:00.

https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-hardware-id

**Comment by PJK2011** [comment]
So there's also the videos and stories about those who have complete or
temporary success putting their motherboards in the oven, or conversely,
some report success after using the freezer. One comment I saw on one such
video said that people are using the oven instead of properly resoldering
the wifi chip.

So I went to the shop today to request my wifi chip be resoldered. The
technician looked at it and said this type of chip can't be resoldered, but
he can try with an electronics heat gun, as I also saw in one video. He did
it more professionally, cleaning and applying flux before applying heat.

This technique brought the board up enough that the Phone Status screen
lost the fake 02:00:00:00:00:00 MAC address. and displayed the MAC address
that your app installed, and but not good enough for the wifi to work, so I
just had him install a motherboard instead.

I put this bad motherboard in another phone retired for a cracked lens, so
I may yet play with it more.

The repair was indeed temporary as 02:00:00:00:00:00 is back again just 2
hours later.

**Comment by ViRb3** [comment]
Have you got any update on the situation? I no longer have that reference Nexus 5 to send you copies of working files, but I can try to help with anything else.

**Comment by PJK2011** [comment]
Thanks for the follow up. I pretty much covered the conclusion of the
matter in the messages above. Your app did help me to confirm hardware
failure (wifi/bluetooth chip solder failure), so I replaced the motherboard.

**Comment by ViRb3** [comment]
Indeed, it sounded like a hardware failure. I hope the new motherboard lasts a good time! If you have any other issues please let me know :)

**Comment by PJK2011** [comment]
Sure will. Thanks for your support.
